- name: Add check_postfix_queue.sh script
  copy:
    src: "files/extends/{{ item.name }}"
    dest: "{{ snmp_extends_path }}/{{ item.name }}"
    owner: root
    group: root
    mode: 0655
    force: true
  when: "inventory_hostname in {{ item.host_check_list }}"
  with_items:
    - { name: check_postfix_queue.sh, host_check_list: check_postfix_queue_hosts }
    - { name: check_meminfo.sh, host_check_list: check_meminfo_hosts }
    - { name: check_raid.pl, host_check_list: check_raid_hosts }
  notify:
    - Restart snmpd
