- name: Install apt packages
  apt:
    name:
     - apt-transport-https
     - software-properties-common

- name: Get apt key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key
    checksum: sha256:ecb3d77aa13d94e1e1abc6b77f6af96665bd62a8255c774ffa0c330fcee8eed4

- name: Set apt repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main
    filename: grafana

- name: Update apt
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install grafana
  apt:
    name: grafana
    state: present

- name: Enable grafana.service
  systemd:
    name: grafana-server.service
    enabled: true
  notify:
   - Reload systemd

- name: Set grafana.ini
  template:
    src: templates/grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: root
    group: grafana
    mode: 0644
    force: true
  notify:
   - Restart grafana

- name: Start grafana
  service:
    name: grafana-server
    state: started