- name: Set exporter_exporter
  block:
    - name: Set facts
      set_fact:
        name: "exporter_exporter"
        download_url: "https://github.com/QubitProducts/exporter_exporter/releases/download/v0.5.0/exporter_exporter-0.5.0.linux-arm64.tar.gz" # homelab-pi
        #download_url: "https://github.com/QubitProducts/exporter_exporter/releases/download/v0.4.5/exporter_exporter-0.4.5.linux-amd64.tar.gz" # vps-01
        sha256sum: "6189effa5b1b1314f8fa95024f180d3ef5445ffaea9a17d0caf5dc2da4d91f93" # raspbian
        #sha256sum: "c274b6dad1c940455ac1d72df00ec57b436c14fab0ac2a685ee39f4ffd3df365" # vps-01
        config_file: "expexp.yaml"
        service:
          start_cmd: "{{ base_path }}/exporter_exporter/exporter_exporter -config.file {{ base_path }}/exporter_exporter/expexp.yaml"

    - include: exporter.yml
  tags: exporter_exporter

- name: Set node_exporter
  block:
    - name: Set facts
      set_fact:
        name: "node_exporter"
        #download_url: "https://github.com/QubitProducts/exporter_exporter/releases/download/v0.5.0/exporter_exporter-0.5.0.linux-arm64.tar.gz" # raspbian
        download_url: "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz" # vps-01
        #sha256sum: "6189effa5b1b1314f8fa95024f180d3ef5445ffaea9a17d0caf5dc2da4d91f93" # raspbian
        sha256sum: "af999fd31ab54ed3a34b9f0b10c28e9acee9ef5ac5a5d5edfdde85437db7acbb" # vps-01
        service:
          start_cmd: "{{ base_path }}/node_exporter/node_exporter"

    - include: exporter.yml
  tags: node_exporter

- name: Set mysqld_exporter
  block:
    - name: Set facts
      set_fact:
        name: "mysql_exporter"
        #download_url: "https://github.com/QubitProducts/exporter_exporter/releases/download/v0.5.0/exporter_exporter-0.5.0.linux-arm64.tar.gz" # raspbian
        download_url: "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz" # vps-01
        #sha256sum: "6189effa5b1b1314f8fa95024f180d3ef5445ffaea9a17d0caf5dc2da4d91f93" # raspbian
        sha256sum: "af999fd31ab54ed3a34b9f0b10c28e9acee9ef5ac5a5d5edfdde85437db7acbb" # vps-01
        config_file: ".mysql_exporter.cnf"
        service:
          start_cmd: |
            {{ base_path }}/mysql_exporter/mysqld_exporter \
            --config.my-cnf {{ base_path }}/mysql_exporter/.mysql_exporter.cnf \
            --collect.global_status \
            --collect.info_schema.innodb_metrics \
            --collect.auto_increment.columns \
            --collect.info_schema.processlist \
            --collect.binlog_size \
            --collect.mysql.user \
            --collect.info_schema.tablestats \
            --collect.global_variables \
            --collect.info_schema.query_response_time \
            --collect.info_schema.userstats \
            --collect.info_schema.tables \
            --collect.perf_schema.tablelocks \
            --collect.perf_schema.file_events \
            --collect.perf_schema.eventswaits \
            --collect.perf_schema.indexiowaits \
            --collect.perf_schema.tableiowaits \
            --collect.perf_schema.memory_events

    - include: exporter.yml
  tags: mysql_exporter
