
#- name: Get file from repo
#  command: "git clone https://github.com/karol-siedlaczek/backup-tool.git > files/"
#  delegate_to: localhost

- name: Fetch backup-tool.py from repository
  git:
    repo: https://github.com/karol-siedlaczek/backup-tool.git
    dest: /usr/local/bin/backup-tool

- name: Fetch remote-task.py from repository
  git:
    repo: https://github.com/karol-siedlaczek/backup-tool.git
    dest: /usr/local/bin/tests


  #delegate_to: localhost