- name: "Create {{ name }} group"
  group:
    name: "{{ name }}"

- name: "Create {{ name }} user"
  user:
    name: "{{ name }}"
    group: "{{ name }}"
    shell: /bin/false
    create_home: false

- name: "Check if {{ name }}.service file exists"
  stat:
    path: "/lib/systemd/system/{{ name }}.service"
  register: old_service_file

- name: "Remove old {{ name }}.service file"
  file:
    path: "/lib/systemd/system/{{ name }}.service"
    state: absent
  when: old_service_file.stat.exists

- name: "Check if /etc/init.d/{{ name }} file exists"
  stat:
    path: "/etc/init.d/{{ name }}"
  register: old_init_script

- name: "Remove old /etc/init.d/{{ name }} file"
  file:
    path: "/etc/init.d/{{ name }}"
    state: absent
  when: old_init_script.stat.exists

- name: Create systemd {{ name }}.service file
  template:
    src: templates/service.j2
    dest: "/lib/systemd/system/{{ name }}.service"
    owner: "{{ name }}"
    group: "{{ name }}"
    mode: 0744

- name: "Add {{ name }}.service to autostart"
  file:
    src: "/lib/systemd/system/{{ name }}.service"
    dest: "/etc/systemd/system{{ name }}.service"
    state: link
    force: yes
    owner: "{{ name }}"
    group: "{{ name }}"
  notify:
    - Reload systemd

- name: "Enable {{ name }}.service"
  systemd:
    name: "{{ name }}.service"
    enabled: true

- name: "Start {{ name }}.service"
  systemd:
    name: "{{ name }}.service"
    state: started

- name: "Create /etc/init.d/{{ name }} script"
  template:
    src: templates/init.sh.j2
    dest: "/etc/init.d/{{ name }}"
    owner: "{{ name }}"
    group: "{{ name }}"
    mode: 0744