- name: "Create {{ service_name }} group"
  group:
    name: "{{ group }}"

- name: "Create {{ service_name }} user"
  user:
    name: "{{ user }}"
    group: "{{ group }}"
    shell: /bin/false
    create_home: false

- name: "Check if {{ service_name }}.service file exists"
  stat:
    path: "/lib/systemd/system/{{ service_name }}.service"
  register: old_service_file

- name: "Remove old {{ service_name }}.service file"
  file:
    path: "/lib/systemd/system/{{ service_name }}.service"
    state: absent
  when: old_service_file.stat.exists

- name: "Check if /etc/init.d/{{ service_name }} file exists"
  stat:
    path: "/etc/init.d/{{ service_name }}"
  register: old_init_script

- name: "Remove old /etc/init.d/{{ service_name }} file"
  file:
    path: "/etc/init.d/{{ service_name }}"
    state: absent
  when: old_init_script.stat.exists

- name: Create systemd {{ service_name }}.service file
  template:
    src: "{{ template.service }}"
    dest: "/lib/systemd/system/{{ service_name }}.service"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744

- name: "Add {{ service_name }}.service to autostart"
  file:
    src: "/lib/systemd/system/{{ service_name }}.service"
    dest: "/etc/systemd/system{{ service_name }}.service"
    state: link
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
  when: startup == "y"
  notify:
    - reload systemd

- name: "Enable {{ service_name }}.service"
  systemd:
    name: "{{ service_name }}.service"
    enabled: true
  when: startup == "y"

- name: "Start {{ service_name }}.service"
  systemd:
    name: "{{ service_name }}.service"
    state: started

- name: "Create /etc/init.d/{{ service_name }} script"
  template:
    src: "{{ template.init }}"
    dest: "/etc/init.d/{{ service_name }}"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 0744